### ISSUE TITLE
Loading presets doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [eldoriarpg/SchematicBrushReborn#167]
Loading presets doesn't work. Global and private presets can be saved correctly, as shown in the wiki, and are then also written to preset.yml. However, if you try to load a preset with `/sbr loadbrush <brushname>` (e.g. `/sbr loadbrush Laub01`), the error message "`Unkown brush`" appears. The presets created are listed in the `/sbrp` overview. However, if you press the info or the remove option, the message "Der Preset Laub01 existiert nicht" appears. A plugin reload or a restart doesn't change the error pattern. The Schematic Tools add-on cannot access the presets either.

Debug: https://plugins.eldoria.de/debug/v1/read/1bd41bac7922b6483f0615a90acdd80027bda5c2
SchematicBrushReborn version 2.2.4
Paper 1.19.2 buid 81
FastAsyncWorldEdit version 2.4.5-SNAPSHOT-276;673b467

**Comment by RainbowDashLabs** [comment]
I think there is a small missunderstanding of the difference between a Brush Preset and a Preset.

Preset contain schematic sets and can only be added to a brush.

Brush presets contain a full brush including all modifiers and schematic sets. Those are used by schematic tools. You are trying to load a preset instead of a brush preset. Because you have a preset named Laub01 but you dont have a brush preset with a name like this. Loading a brush named Laub1 would work since you have this one.

Maybe this makes it more clear https://github.com/eldoriarpg/SchematicBrushReborn/wiki/Presets

**Comment by aerulion** [comment]
But loading presets when creating a new brush does not work either.
For example I saved a personal preset named _bloodTree_, which is also stored inside the preset.yml:
```
  - ==: de.eldoria.schematicbrush.libs.eldoutilities.serialization.wrapper.MapEntry
    key: a12c8668-efc2-48af-8d44-e3fad9801350
    object:
      ==: sbrYamlPresetContainer
      presets:
      - ==: sbrPreset
        name: bloodTree
        description: none
        sets:
        - ==: sbrSchematicSetBuilder
          selector:
            ==: sbrDirectorySelector
            term: '*'
            directory: fawe/bloodTree
          modifiers:
          - ==: de.eldoria.schematicbrush.libs.eldoutilities.serialization.wrapper.MapEntry
            key: Flip
            object:
              ==: sbrFlipRandom
          - ==: de.eldoria.schematicbrush.libs.eldoutilities.serialization.wrapper.MapEntry
            key: Rotation
            object:
              ==: sbrRotationRandom
          weight: -1
      uuid: a12c8668-efc2-48af-8d44-e3fad9801350
```
When adding the preset in the schematic-set menu it is recognized by the tab-completion (https://i.imgur.com/et8bobk.png), but it does not apply correctly. (Also with the error message 'Unknown preset')
A similar way of reproducing is using the /sbrp command to list all presets. When clicking on the 'Info' button a similar error message appears (https://i.imgur.com/hDN9ubJ.png).
